### ISSUE TITLE
how to disable only the boolean gate ?

### ISSUE THREAD

**Issue by deepak** [jnunemaker/flipper#139]
there is a `Flipper::Feature.disable_actor` 
but there is no corresponding  `Flipper::Feature.disable_boolean` 

does the API support this ?

when I add a new method. 

```
def disable_boolean(actor)
  disable Types::Boolean.wrap(true)
end
```

It does not work as advertised. 
copied verbatim from `disable_actor`

this is because for the activerecord adapter, the boolean gate clears out all the gates

eg:

```ruby
require 'flipper'
require 'flipper/adapters/active_record'

adapter = Flipper::Adapters::ActiveRecord.new
flipper = Flipper.new(adapter)

Product = Struct.new(:id) do
  def flipper_id
    "product:#{id}"
  end
end

product1 = Product.new(1)
product2 = Product.new(2)

flipper[:search].enable
flipper[:search].enable(product1)

# now the flipper_gates table has

# +----------------+-----------+--------------+
# | feature_key | key        | value         |
# +----------------+-----------+--------------+
# | search         | actors    | product:1  |
# | search         | boolean | true           |
# +----------------+-----------+--------------+

# clears out everything and the flipper_gates table is empty
flipper[:search].disable

# clears out actor and keeps the boolean gate

flipper[:search].disable(product1)

# now the flipper_gates table has

# +----------------+-----------+--------------+
# | feature_key | key        | value         |
# +----------------+-----------+--------------+
# | search         | boolean | true           |
# +----------------+-----------+--------------+

```

**Comment by jnunemaker** [comment]
`enable` is for enabling the boolean gate and `disable` is for disabling it. No need for another method.

**Comment by jnunemaker** [comment]
Let me know if that wasn't clear or if you have any other questions. I just realized that answer was kind of short, but I'm not really sure what else to say.

**Comment by deepak** [comment]
am using the `active_record` adapter and i have:
- a bolean gate
- an actor gate

when i use the `disable_actor` it disables *only* the actor gate
but when i use `disable` it disables *both* the boolean and the actor

was asking if it it possible to add a `disable_boolean` method like the `disable_actor` method

**Comment by jnunemaker** [comment]
It is not. disable with a boolean clearing all the values is intentional. It would be very confusing to enable a feature for an actor, enable the feature for everyone (boolean), then disable the feature (boolean) and find out that it was still enabled for the actor. When someone clicks disable or types it in a console, I want to ensure that it completely disables everything. 

Perhaps if you explain the higher level use case I can provide some help.

**Comment by deepak** [comment]
> Perhaps if you explain the higher level use case I can provide some help.

A feature eg. search, starts out being enabled for an Actor

we have our own UI and a product manager can globally enable a feature
at which time it cannot be changed from the UI
using a boolean gate for globally enabling a feature

At this time, both the boolean and the actor gates are in the database
nothing has been deleted

want to provide two possibilities for the product manager:

1. we made a mistake in enabling the feature, it is too early,
    so disable only the boolean gate and the old actor gates remain as is
2. everything is good, so cleanup and delete the old actor gates. the new boolean gate remains as is

I can keep track of the feature state separately, and ask the feature for its actor
for a global feature, it returns an object whose `flipper_id` is `global`
for a non-global feature, it returns the `current_site` (our tenant) so `flipper_id` is 'Site:1` or `Site:20` etc
and write a wrapper for checking if the feature is enabled

But it is a legacy app. and it was easier to not do this
- track the state of a feature. global or actor
- write a wrapper for the actor

right now, am manually deleting the boolean gate
was hoping for a `disable_boolean` API to disable only the global feature toggle

**Comment by jnunemaker** [comment]
I guess the issue is even if you make a disable_boolean method, it won't work. The clearing of everything when disabling a boolean happens at the adapter level and even has a test. We'd have to actually change the way flipper works in that regard, which would be a pretty big breaking change, so I'm very hesitant to do so. If I get a lot more feedback that this is the expectation by people using flipper, I'd be happy to sit down and think it through, but as of right now this is the first I've heard of it being a problem, so I'm inclined to keep things the way they are. I'll definitely keep this in mind and if I (or you) can come up with some other way, I'd definitely be willing to consider it.

**Comment by deepak** [comment]
@jnunemaker thanks for answering

**Comment by gmac** [comment]
I agree with @deepak – I find the way Flipper purges actor settings to be extremely destructive, and makes it way too easy to blow away carefully composed feature whitelists with simple tinkering.

**Comment by jnunemaker** [comment]
@gmac thanks for voicing up here. I do want to know if this is a common thing with people.

**Comment by tleish** [comment]
+1 for a temporary kill switch.

We have run into the same issue.  While using flipper to roll out a group of beta features to a bunch of users, we discovered a major issue with the feature.  We quickly disabled the feature gate, but then realized it wiped out all the users who had signed up to beta test the feature.  Had we know this, we would've backed up the flipper data before disabling the feature.  Then restored after a fix was deployed.  Either way, it's a bit of a pain.

If this was 2 to 5 users, not big deal.  But this was around 100+ users.

Basically, create a solution that allows temporary disable of a feature when you find a major issue, then rollout the feature to the same group of people again without loosing the enrollment data.

A few options on how this could be implemented:
1. One way would be to add a flag on the switch and create a differentiation between enabled/disabled.  This approach would allow you to disable all users who use a feature, and then slowly turn them on one-by-one without loosing data.
2. Since the scenario is a temporary disable, another different option might be to use the flipper cache(e.g. Redis) as a wrapper to globally enable/disable a feature.  This is a simpler approach.  It doesn't allow you to turn back on users one-by-one, but I think the one-by-one is less common.  If this was an occurrence, you can still handle the urgent "disable this feature now!" scenario quickly without deleting data, and then backup the data and manually restore users one by one.
