### ISSUE TITLE
Redis cache adapter

### ISSUE THREAD

**Issue by AlexWheeler** [jnunemaker/flipper#142]
Redis adapter to cache adapter calls just like the Dalli Memcached adapter

**Comment by jnunemaker** [comment]
I guess I'd be fine with that. We have a redis adapter already, but perhaps people cache with redis in a way that they still want persistent flipper data elsewhere.

**Comment by AlexWheeler** [comment]
yes I thought I'd just make the issue in case anyone wants to work on it since seems to me that its pretty common to store Flipper data in Postgres and then use Redis as a cache

**Comment by camallen** [comment]
I have a use case for a Postgres and a Redis cache adapter and am keen to contribute to the awesome sauce that is flipper. 

Since a Redis adapter already exists, I was thinking of modifying it to mimic the [Dalli one](https://github.com/jnunemaker/flipper/blob/dfdaa8265fe8ffc29666493663678d1fbc5bab87/lib/flipper/adapters/dalli.rb#L26) so that it can take an adapter as well as the redis client. However we want to preserve existing adapter behaviour, e.g. the cache adapter should auto expire keys via a TTL but the persistent storage adapter shouldn't. 

Any thoughts on implementation details? Would you prefer two distinct adapters instead of a single one?

**Comment by AlexWheeler** [comment]
@camallen awesome, I think others would benefit from this too. I'd say a different adapter is the way to go (@jnunemaker probably has some thoughts). Its easier to implement and maintain the two separately, and fits the concept of a cache adapter: https://github.com/jnunemaker/flipper/blob/master/docs/Optimization.md#user-content-cache-adapters 

Looking at `lib/flipper/adapters/memoizable.rb`, and `lib/flipper/adapters/dalli.rb` should point you in the right direction.

**Comment by jnunemaker** [comment]
@camallen I'm with @AlexWheeler. I would create a second redis adapter in the flipper-redis gem. No need for a new gem/gemspec or anything. RedisCache would be fine as a name for me. Making it work like the dalli one would be ✨ .

**Comment by ronaldtse** [comment]
We have a similar use case and would be awesome to have a cache adapter for Redis!
