### ISSUE TITLE
Gem dependency conflict over rack-protection

### ISSUE THREAD

**Issue by ryanswood** [jnunemaker/flipper#153]
Hello. I am working on moving to Rails 5 and am getting a gem dependency conflict. I am using a few gems that require the use of Sinatra which means that I have to use the 'master' version in order to get Rack 2 support to satisfy Rails 5.

Now I am seeing this error when trying to bundle:

```
Bundler could not find compatible versions for gem "rack-protection":
  In Gemfile:
    flipper-ui was resolved to 0.9.1, which depends on
      rack-protection (~> 1.5.3)

    sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack-protection (~> 2.0)
```

I first off thank you for this gem and all the time that you take to maintain it. I am not well versed in 'rack-protection.' With that said, is there a possibility you can open up the allowable versions for the 'rack-dependency' to include 2.0.0 which is on master?

**Comment by jnunemaker** [comment]
> I first off thank you for this gem and all the time that you take to maintain it.

🙇  Kind of you to say that!

>  I am not well versed in 'rack-protection.'

I use it for CSRF protection if I remember right. Otherwise it could perhaps be possible for an attacker to craft a form that would enable/disable a feature in your app by guessing the feature name and doing some other trickery.

> With that said, is there a possibility you can open up the allowable versions for the 'rack-dependency' to include 2.0.0 which is on master?

Seems fine, though I don't really know the implications. :) Looks like rack-protection only has a beta release:

![screen shot 2016-08-22 at 1 58 02 pm](https://cloud.githubusercontent.com/assets/235/17865425/89ca9424-6870-11e6-8e8e-ea572ec45770.png)

...so I'm not sure if <= 2.0 would even work. I suppose I could do < 2.1.0 and that would get it, I would think. Could you try locking to [this branch](https://github.com/jnunemaker/flipper/compare/rack2) and let me know if it works for you or let me know of a better way to handle this?

**Comment by jnunemaker** [comment]
Travis-ci passed as it used rack 1.5.3, but when I tested against 2.0.0.beta2 locally I got several failures, so it probably is going to require more work than just relaxing the dependency.

**Comment by jnunemaker** [comment]
Ok, got it fixed in the rack2 branch and tested locally against rack-protection 2.0.0.beta2 with no issues. Only thing that would be useful is for someone to verify that the gemspec is good to go for them. If someone in this situation could let me know if https://github.com/jnunemaker/flipper/pull/156 works for them, that would be great. Thanks!

**Comment by ryanswood** [comment]
I think we are good to go! I was able to resolve my dependency issue both with your branch and a similar change I had in my fork of Flipper that I was testing locally.

**Comment by jnunemaker** [comment]
0.9.2 should be out now and has the fixes in it. Let me know if that doesn't fix this for you. Closing the issue as I believe it will.
