### ISSUE TITLE
Can't mass-assign protected attributes: key

### ISSUE THREAD

**Issue by TLmaK0** [jnunemaker/flipper#161]
```Can't mass-assign protected attributes: key``` when creating a new feature with flipper ui and Flipper::Adapters::ActiveRecord. Adding ```attr_accessor :key``` to the adapter workaround the problem.

**Comment by AlexWheeler** [comment]
@TLmaK0 thanks, which version of rails are you on?

**Comment by TLmaK0** [comment]
@AlexWheeler Rails 3.2.14

**Comment by AlexWheeler** [comment]
great, did you add `attr_accessor :key` or `attr_accessible :key`? `attr_accessor :key` attr_accessible is a rails method for allowing specific attributes to be mass assigned and would fix your issue.

The problem with adding it to the adapter is that attr_accessible has been taken out of rails versions > 4.0.  It looks like you'll also have issues with enabling gates via the UI since the adapter code uses mass assignment there too.  

@jnunemaker curious on your opinion on this.
Changing the code to not use mass assignment and instead do something along the lines of
`
feature_class.create! do |f|
  f.key = 'key'
  etc.
end
`
over `feature_class.create!({ mass assigned attrs })` would make this work with all versions of active record or we could check the version at runtime

```
if Gem.loaded_specs['activerecord'].versiom > Gem::Version.new("4.0.0")
  attr_accessible(:key)
end
```

other thoughts?

**Comment by TLmaK0** [comment]
@AlexWheeler 
You are true. I used ```attr_accessible```, sorry :(
And as you say, I have also problems with Gates (attributes :key, :value, :feature_key)
Thanks 👍

**Comment by jnunemaker** [comment]
@AlexWheeler I should have written up my thoughts. Sorry. Yeah, I was thinking we just don't use mass assignment and then we can avoid the issue. Something like this:

```ruby
instance = @gate_class.new
instance.feature_key = feature.key
instance.key = gate.key
instance.value = thing.value.to_s
instance.save!
```

Same thing for other gate and feature usages. I just hadn't whipped a PR together yet. If someone wanted to that would be great.

**Comment by AlexWheeler** [comment]
cool will get a PR up tonight, thanks
