### ISSUE TITLE
Enabling a feature for a fixed amount of time

### ISSUE THREAD

**Issue by jacksonh** [jnunemaker/flipper#208]
One of the things I'm exploring using Flipper for would be enabling a feature for a short period of time. Like "enable this feature for the next 2 hours". Is that something other people would be interested in, or something that's already supported?

**Comment by jnunemaker** [comment]
Interesting idea. No current plans to support this currently (as you are the first to bring it up), but it is something that would be trivial to implement once #163 is complete.

For now, the best thing I could suggest is perhaps a cron or timed task that disables the feature for you. Thanks again for dropping the idea here!

**Comment by oliverswitzer** [comment]
+1 this would be super awesome to have! Might I add a simpler use case that would be jus to specify a feature to be enabled after a specific date/time. 

We're releasing something over thanksgiving while people are out of office and it would be awesome if we could specify a time for a feature to toggle on automatically rather than have someone interrupt their break to do it.

**Comment by maboelnour** [comment]
Any updates related to this feature?

**Comment by jnunemaker** [comment]
Nope.

**Comment by jnunemaker** [comment]
Sorry I mean no updates. It can be implemented with from or any sort of scheduling software. Some background jobs support scheduling things. Nothing native in flipper though.

**Comment by t1mwillis** [comment]
@jnunemaker I would be interested in helping implement this feature. Is there anything specifically I can do to help?

**Comment by jnunemaker** [comment]
#557 will make this possible so I'm closing this issue for now.
