### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by avit** [jnunemaker/flipper#261]
I was reviewing Flipper and how to apply it to our Rails app, when I started looking into the memoization code to see how it's meant to be used. My understanding is there needs to be a Singleton instance such as `App.flipper` that holds the memoized state between every call to check features.

Am I right that the middleware clears the memoized features around each web request? Since this is happening on the cache instance variable in Memoizable (via `flipper.adapter.memoize = true`), it looks like concurrent threads would be continuously clearing over each other's caches.

There is a note in the [changelog for version 0.7][1] about thread safety:

> * Moved memoizable decorator to instance variable storage from class level thread local stuff.
>   Now not thread safe, but we can make a thread safe version later.

I expect this is still the case? Was there a reason not to keep the cache storage in a `Thread.current` variable?

Or, would it make more sense for us to initialize our "Singleton" flipper instance in a thread local instead, something like this?

```
def App.flipper
  Thread.current[:flipper] ||= Flipper.new(*@flipper_options)
end
```

Related to this, I might want a middleware for Sidekiq if the Rack middleware doesn't "just work". 😄  Could this be a useful contribution to the project? I'll see what makes sense based on the above.

Thanks!

[1]: https://github.com/jnunemaker/flipper/blob/master/Changelog.md#07

**Comment by jnunemaker** [comment]
> Or, would it make more sense for us to initialize our "Singleton" flipper instance in a thread local instead, something like this?

This is what I'm doing for an app that uses puma with threads. I still need to audit to ensure that all the pieces of flipper are safe if used in this manner, but its been working for me thus far in production. 

I'd be open to a thread safe memoized adapter as well. I just haven't gotten around to it. Maybe if we just use Thread.current in the memoized adapter we can avoid the synchronization?

> Related to this, I might want a middleware for Sidekiq if the Rack middleware doesn't "just work". 😄 Could this be a useful contribution to the project? I'll see what makes sense based on the above.

I'd be open to this. I think the main key is that I'd want a separate gem (say flipper-sidekiq) so it can have an official gem dependency but not be required for flipper itself (since not everyone uses sidekiq).

**Comment by avit** [comment]
Thanks for the quick reply.

> Maybe if we just use Thread.current in the memoized adapter we can avoid the synchronization?

I think that makes sense. For now I'm going to reload the Flipper instance per-thread as you are doing, instead of relying on the middleware.

Besides clearing the memoization, another thing to consider with thread safety is whether all the connection adapters themselves are threadsafe (dalli, etc.) or if they need something like a connection pool wrapped around them. ActiveRecord connection already does this, and it might not be a concern if the main use case is read-only anyway.

**Comment by jnunemaker** [comment]
@avit yeah, definitely a great point. My plan was to document that. Since most adapters take an instance of the database client, rather than configuration to build an instance, it should be easy for people to wrap the client with a thread pool prior to passing to the adapter. If the adapters need changes, we could always tweak them or provide TheadSafe* versions with docs.

**Comment by jondavidjohn** [comment]
Ahh, was using the memory adapter in test.  Swapped it out for the pstore and it's working as expected, just have to add clearing/resetting to my spec helper to ensure I'm not retaining state between runs in the file.

**Comment by jnunemaker** [comment]
@jondavidjohn glad you figured out your problem. Perhaps we should make a thread safe memory store adapter or just make the memory store adapter thread safe. Were you using a global or the flipper default instance stuff?

**Comment by jondavidjohn** [comment]
Was just using the default instance I believe with the `Flipper.xxxx` static methods.

Still not convinced it's an issue with thread safety as much as it is a problem with the process paradigm that capybara drivers use.  I'm thinking that because the memory adapter is process specific the second you introduce any sort of multi-process flows it breaks down, which is why the pstore worked because it's shared among the processes.

**Comment by erikaxel** [comment]
I just came across the exact same problem.  The solution for us was also to use PStore, but I think there should be a memory solution available. We are able to share other variables across capybara and testing processes, so there should be a way, although I'm not sure how. Also just want to mention that I had to put the Flipper and Adapter initialization out of the configuration block, or else it would reinitialize a bunch of times which caused issues. I ended up with the following code which seems to work fine: ```if Rails.env.test?
  adapter = Flipper::Adapters::PStore.new('tmp/flipper.test.pstore')
else
  adapter = Flipper::Adapters::Memory.new
end

flipper = Flipper.new(adapter)

Flipper.configure do |config|
  config.default do
    flipper
  end
end
```

**Comment by jondavidjohn** [comment]
Could find it after a quick look, but is there a ‘Flipper.reset’ method?  That’d be really useful in this situation in a global ‘before’ block since we’re having to use the PStore.

**Comment by xaviershay** [comment]
If I'm reading #279 correctly, I think this issue has been addressed?

**Comment by jnunemaker** [comment]
@xaviershay yes and no. All depends on what adapter you are using. Flipper itself should be pretty thread safe. As long as you initialize a new instance of the adapter (and thus new connection) or use an adapter that is thread safe (like a thread pool or whatever) then you should be fine. I use flipper with puma/active record and no problems currently.

**Comment by xaviershay** [comment]
Thanks. I'm also using with puma/active_record.

**Comment by jnunemaker** [comment]
I'm going to say this is safe. I've been using flipper with puma/threads for a while without issues. The key is a flipper instance per thread to ensure your adapter is safe. Certainly possible to do one instances of flipper across threads if you have thread safe adapter, but not sure that I'm going to provide those out of the box since instance per thread works fine.
