### ISSUE TITLE
ActiveRecord adapter unavailable from flipper/adapters/active_record

### ISSUE THREAD

**Issue by Orbyt** [jnunemaker/flipper#287]
The example shown [here](https://github.com/jnunemaker/flipper/blob/v0.10.2/examples/active_record/basic.rb) uses the following to import the `ActiveRecord` adapter: `require 'flipper/adapters/active_record'`

However, using this in code results in an `uninitialized constant Flipper::Adapters::ActiveRecord` error. Additionally, executing `Flipper::Adapters.constants` in the Rails console results in the following:

`=> [:Memoizable, :Memory]`

Visiting [this page in the docs directory](https://github.com/jnunemaker/flipper/tree/v0.10.2/docs/active_record) instructs the user to install the `flipper-active_record` gem instead.

How come the `ActiveRecord` adapter is not accessible via `flipper/adapters/active_record` as shown in the example, when the class is clearly present in the source? Alternatively, why does a separate part of the documentation specify the need to install a separate gem? Where is the source for that specific gem?

**Comment by AlexWheeler** [comment]
@Orbyt that's a great question!  Thanks for the super descriptive issue.

**How come the ActiveRecord adapter is not accessible via flipper/adapters/active_record as shown in the example, when the class is clearly present in the source?**

All of the source code lives in this repository, but you'll notice in the root directory there are multiple 
`.gemspecs` so that each adapter can be packaged separately.  

e.g.
* [flipper-active_record.gemspec](https://github.com/jnunemaker/flipper/blob/master/flipper-active_record.gemspec)
* [flipper-redis.gemspec](https://github.com/jnunemaker/flipper/blob/master/flipper-redis.gemspec)
* [flipper-mongo.gemspec](https://github.com/jnunemaker/flipper/blob/master/flipper-mongo.gemspec)

Flipper users explicitly install the adapters they need to use.  This way an ActiveRecord user that has no need for a mongo adapter doesn't download all of the mongo code.

If you're curious how this works you can take a look at the [flipper.gemspec#L13](https://github.com/jnunemaker/flipper/blob/master/flipper.gemspec#L13) and notice that all other `gemspecs` are ignored when packaging the flipper gem.

**executing Flipper::Adapters.constants in the Rails console results in the following:**
`=> [:Memoizable, :Memory]`

The Memoizable, and Memory adapters are not packaged as separate gems and are included when you `gem install flipper` - they don't depend on third party dependencies like ActiveRecord, or Mongo.

**Alternatively, why does a separate part of the documentation specify the need to install a separate gem?**

Maybe together we can make this more clear that this assumes you have installed flipper-active_record.  Would love to hear your thoughts.

**Comment by Orbyt** [comment]
@AlexWheeler I appreciate the thorough response. 

I went into my local gem installation directory of the Flipper gem and noticed the `flipper/adapters/` directory was in fact a bit different than shown in this repository. I assume that this is caused by the following lines in the `flipper.gemspec` file you mentioned:

```
Dir['flipper-*.gemspec'].map do |gemspec|
  spec = eval(File.read(gemspec))
  plugin_files << spec.files
  plugin_test_files << spec.files
end

ignored_files = plugin_files
```

Is this correct?

Regarding the following:

>Maybe together we can make this more clear that this assumes you have installed flipper-active_record. Would love to hear your thoughts.

I think the `require 'flipper/adapters/active_record'` statement found in [active_record/basic.rb#L17](https://github.com/jnunemaker/flipper/blob/master/examples/active_record/basic.rb#L17) is slightly confusing. 

Perhaps a small comment mentioning the separate gem needs to be installed above that line would be helpful. Including some of the information you've just mentioned here would be helpful on the [ActiveRecord adapter documentation](https://github.com/jnunemaker/flipper/tree/v0.10.2/docs/active_record).

I'm happy to submit a PR if you think it would be a good addition.

**Comment by jnunemaker** [comment]
@AlexWheeler thanks for the great explanation. You rock. 

@Orbyt This repo works like a mono-repo where there are several projects in one. It makes it more confusing for situations like this, but way less work from a maintenance standpoint. I also like that all the code is together in one place (so you don't have to hunt around for multiple repos). Having gone the multiple repo route on other similar projects, I can say I like the mono-repo better. 

The confusion hasn't come up yet, but I REALLY appreciate you reporting it. I'm sure others have as well but didn't have the time or energy, so thank you!

**Comment by jnunemaker** [comment]
> I'm happy to submit a PR if you think it would be a good addition.

I'd love to see what you come up with.

**Comment by Orbyt** [comment]
I added a very small PR including the comment I indicated would be useful above. Frankly, I think the majority of my confusion arose due to being a newcomer to the Ruby/Rails community. The clarification on how the project is packaged into separate gems makes things make a little more sense.

I'll continue to give the documentation some thought and will submit further PR's if necessary.
