### ISSUE TITLE
Basic Auth around UI using Rack::Auth::Basic

### ISSUE THREAD

**Issue by kevinjalbert** [jnunemaker/flipper#292]
I'm trying to insert _Basic Auth_ around the Flipper UI in my route.rb with the following:

```ruby
    flipper_app = Flipper::UI.app(Flipper.instance)
    flipper_app.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.secrets.flipper_username)) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.secrets.flipper_password))
    end
    mount flipper_app, at: "/flipper"
```

The exact same approach works for [Sidekiq::Web](https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes), and I was expecting it to function the same way with Flipper UI. I'm not too sure why this is the case. Any suggestion?

**Comment by jnunemaker** [comment]
It might be because I [run a default app](https://github.com/jnunemaker/flipper/blob/c4a21569b223aab17e9b5f2e4d9ef36164e4d4c8/lib/flipper/ui.rb#L47). 

The `app` method [yields a builder instance](https://github.com/jnunemaker/flipper/blob/c4a21569b223aab17e9b5f2e4d9ef36164e4d4c8/lib/flipper/ui.rb#L40) prior to any other middleware that I setup. I think you want to use that:

```ruby
Flipper::UI.app(Flipper.instance) do |builder|
  builder.use Rack::Auth::Basic do |username, password|
    ...
  end
end
```

Can you give that a try and let me know if it solves your problem? Another option is to use constraints [as described in the docs](https://github.com/jnunemaker/flipper/blob/c4a21569b223aab17e9b5f2e4d9ef36164e4d4c8/docs/ui/README.md#security). Closing the issue to keep things tidy but happy to help more.

**Comment by kevinjalbert** [comment]
@jnunemaker that worked perfectly! Thanks for the insight and suggestion.

Could be worth putting that in the docs as another option?

**Comment by jnunemaker** [comment]
@kevinjalbert yeah, I could see that. Would you have any interest in creating a pull request to add it there? 😉

**Comment by kevinjalbert** [comment]
@jnunemaker I'll get to it tonight :)

**Comment by jnunemaker** [comment]
@kevinjalbert oh snap. You are on the hook now.

**Comment by kevinjalbert** [comment]
@jnunemaker readme updated in https://github.com/jnunemaker/flipper/pull/293 :)
