### ISSUE TITLE
Flipper.register Redis

### ISSUE THREAD

**Issue by tridnguyen** [jnunemaker/flipper#294]
I'm using the redis adapter for flipper to a redis instance on a separate url.  When I try to register a group with Flipper.register, it does not use the redis adapter.  It appears to be registering the group in memory.  The group gets registered, but doesn't show as registered in the flipper UI or from the console if I create a new flipper instance with the redis adapter.  Is there a config I'm leaving out when I register the group?

Looking at the code block for Flipper::Registry.new, it looks like an adapter can't be specified and the methods called on the registry won't work with redis.

**Comment by jnunemaker** [comment]
That is correct. register only does so in memory for performance reasons. I didn't want a Flipper.register call that gets invoked on boot of the app to do a network call to a service that could possibly be down and thus prevent the application from booting. 

The downside is if you mount the flipper UI outside of where the register calls happen, groups won't show up in the UI. I've thought of a few ways of tackling this, but no one has brought it up so I've avoided it. 😄  

One thought I had was to have a `Flipper.sync_groups` or something command that would do a single network call for all registered groups and store the results in the adapter for sharing with the UI. The problem really is that we can only store the groups name as storing dynamic ruby code wouldn't make sense and could be a huge security risk.

What we did for [featureflipper.com](https://featureflipper.com) is make group a text field instead of a drop down. Not ideal, but still makes it so groups can be enabled by typing in the name. Perhaps the OSS UI should support this as well until we have a solution for storing registered groups at the adapter level.

featureflipper.com enable group text field:
<img width="671" alt="featureflipper-text-field" src="https://user-images.githubusercontent.com/235/31454180-94793d5e-ae82-11e7-8620-37bde5fd9a72.png">

OSS UI enable group select:
<img width="492" alt="ui" src="https://user-images.githubusercontent.com/235/31454184-98106b5e-ae82-11e7-9343-ae1111a95d90.png">

@tridnguyen any thoughts on any of that context/information above?

**Comment by tridnguyen** [comment]
@jnunemaker everything you stated makes sense.  For me, it's not just the groups not showing in the UI that is a problem.  The problem I'm having is actually registering the group.  I'm running on heroku and a rails console to a heroku dyno is ephemeral.  If I register the group in memory in that dyno from the console, it will register, but only in memory for that dyno.  The actual dyno that is serving up the web server won't see the group registered.  I would basically have to register the group whenever a dyno is spun up.

**Comment by jnunemaker** [comment]
@tridnguyen the group has to be registered in the code that executes it or how will it know how to evaluate if the group returns true or false for the provided actor?

**Comment by AlexWheeler** [comment]
@tridnguyen that's correct.  You can register it in your Flipper initializer *config/initializers/flipper.rb* which will get run any time the app boots, which will happen any time a dyno is spun up.

**Comment by tridnguyen** [comment]
@AlexWheeler I didn't even think about putting it in the initializer, that worked perfectly thanks!

**Comment by jnunemaker** [comment]
@tridnguyen any thoughts on where we should doc this or how to improve usage so future flipper users don't end up confused?

**Comment by tridnguyen** [comment]
@jnunemaker I think if the docs were updated to state that groups are registered in memory, not in the adapter specified and should be registered whenever the application starts, it should be sufficient to avoid confusion.
