### ISSUE TITLE
Flipper gates cannot be audited 

### ISSUE THREAD

**Issue by abelvarga** [jnunemaker/flipper#394]
Hi!

We are using Audited gem to audit all changes deemed important. We would like to audit flipper gate changes. Create works OK, but the active record adapter uses `delete_all` which bypasses all callbacks. This makes actor removals not auditable.

Could we just use `destroy_all` instead or is there a known drawback?

Happy to open PR if there's no objection!

Cheers,
Abel

**Comment by jnunemaker** [comment]
The primary reason was to reduce network calls (1 in delete_all vs many in destroy_all), but the uses of delete_all are all for writes so that probably isn't a huge concern. I do my best to keep reads (the hottest path in any app) to be the minimum network calls and sometimes it carries over into writes. I'd be open to a PR that changes this for sure.

**Comment by abelvarga** [comment]
@jnunemaker, just opened the PR. Please advise on if I need to add specs or not. I'm guessing the latter.

Also, some CI tests fail on bundler issues. Should I be concerned? Or is that to be expected?

**Comment by jnunemaker** [comment]
@abelvarga I wouldn't be concerned. Likely a travis environment thing.

**Comment by abelvarga** [comment]
@jnunemaker, thanks for the merge! When can we expect a release?

**Comment by abelvarga** [comment]
@jnunemaker, is this a breaking change?

**Comment by jnunemaker** [comment]
Releasing 0.16.1 now!
