### ISSUE TITLE
Enabling a feature for everyone should clean up old gate records in AR adapter

### ISSUE THREAD

**Issue by xaviershay** [jnunemaker/flipper#422]
I'm not sure if this is adapter specific or not, but say I've created a heap of gate records for specific customers:

```
flipper[:feature].enable(customer_1)
flipper[:feature].enable(customer_2)
flipper[:feature].enable(customer_3)
```

I then enable for all:

```
flipper[:feature].enable
```

I would expect this to "clean up" all the old customer records, but it doesn't. Now, on each feature load all 4 gates will be loaded, despite the fact that the last one makes the first three redundant.

Of course, the performance isn't any _worse_ than you originally had, but if you realise that you've created too many gates then enabling for everyone seems like it _should_ fix it for you. Also, just feels gross to leave around redundant gates.

A workaround is:

      ActiveRecord::Base.transaction do
        flipper[key].disable # Warning: this issues a `DELETE` per gate, so may take a long time.
        flipper[key].enable
      end

I'm happy to investigate a patch for this if you think it sounds reasonable? Let me know.

**Comment by xaviershay** [comment]
hrmm, something fishy might be going on. Inspecting the code, it appears to be already trying to do this: https://github.com/jnunemaker/flipper/blob/master/lib/flipper/adapters/active_record.rb#L125

**Comment by gshutler** [comment]
I think the current behaviour is desirable. Say you want to enable it for everyone, but then have to roll back for some reason. Currently it will be a step back to where you were previously. If it were to tidy up aggressively then it would end up being enabled for no-one and you'd have to remember it was customer 1, 2, and 3 (per your example) that it was enabled for.

**Comment by xaviershay** [comment]
I hadn't considered the rollback scenario, and I think I agree with you about that being desirable. However, the current API doesn't allow for it I don't think - you'd have to monkey around with private APIs. If you do a boolean `enable!` followed by a `disable!` it won't rollback - it will delete all gates!

**Comment by jnunemaker** [comment]
First, the intention is definitely to clear everything once enable or disable happens. The reason is that hitting disable and having it reverting back to the previously enabled things would be confusing. Imagine you enable customers 1, 2 and 3. Then you hit fully enable to turn it on for everyone. Then something is wrong so you hit fully disable. The code intends to have nothing enabled at this point. If the code reverted to customers 1, 2 and 3 being enabled, that would be confusing (BUT I HIT DISABLE BECAUSE STUFF IS HITTING THE FAN PLEASE NO :)). 

If you aren't seeing this behavior, then I'm confused. I used a transaction on the active record adapter so outside of a race (which seems unlikely for enable/disable as they shouldn't be happening very often simultaneously, things should be getting cleaned up. 

@xaviershay can you get a failing test or spec for this or an example gist? Something I can execute would be really helpful. Also, what versions of flipper/flipper-active_record are you using (just to double check)?

**Comment by xaviershay** [comment]
yeah I'll poke around and figure out what's going on! Going to close and assume it's something weird in my env, will re-open if I discover otherwise.

**Comment by yjukaku** [comment]
@jnunemaker I think this should be reopened. This is also happening with percentage rollouts. Steps to reproduce:

1. Enable a feature for X% of users (eg. 50%).
2. Click to "Enable" for everyone

You'd expect the 50% gate to be cleared, but it's not.

![Screen Shot 2019-12-23 at 2 23 35 PM](https://user-images.githubusercontent.com/908365/71376539-d4dc9b80-258f-11ea-9c1a-1cbae0ccae82.png)

**Comment by jnunemaker** [comment]
@yjukaku thanks! I'll take a peak.
