### ISSUE TITLE
Minor issue: 100% rollout results in confusing UI

### ISSUE THREAD

**Issue by yjukaku** [jnunemaker/flipper#463]
So recently we wanted to rollout a feature to all of our logged in users, but not for our logged out users. Our code simply had this check, though:

```
if Flipper.enabled?(:cool_new_feature)
  show_cool_new_feature
end
```

So instead of clicking "Enable" in the UI, we simply set the rollout percentage to 100%.

That worked. Guest users don't get the feature, and all logged in users do.

However, the web UI seems to be a bit confused. 
In both screenshots, the green icon should probably be yellow: 

![Screen Shot 2020-06-01 at 1 18 48 PM](https://user-images.githubusercontent.com/908365/83435569-8074fc00-a40a-11ea-887a-684be8129452.png)

--- 

![Screen Shot 2020-06-01 at 1 18 32 PM](https://user-images.githubusercontent.com/908365/83435922-ff6a3480-a40a-11ea-958c-c584e20d71ad.png)

**Comment by jnunemaker** [comment]
Right or wrong, this is intentional. The color of the squirrel is based on the feature state and the feature state returns :on for 100% actor or time gates. 

https://github.com/jnunemaker/flipper/blob/ef819f3f286920479c6304be4328e7f180ef187b/lib/flipper/feature.rb#L208

I believe this was requested by github people when we implemented it there. 

I think the idea was that anything that is 100% on is fully enabled so might as well show it as the same even though it isn't using the boolean gate. The tricky thing though is that 100% of actors might only include signed in actors so it might not be fully enabled. 100% of time would be equivalent to the boolean gate though. 

Maybe 100% of actors should stay conditional? I could be talked into that. Any of that make sense or cause any strong feelings either way for anyone?

**Comment by yjukaku** [comment]
It makes sense to me that 100% of actors is considered conditional, especially since the default configuration is that only signed in users are considered in the `percentage_of_actors`.
