### ISSUE TITLE
How to access session in instrumentation?

### ISSUE THREAD

**Issue by asterite** [jnunemaker/flipper#484]
Right now you can add instrumentation so that you know when a feature was enabled or disabled, but if there's a user in the session there's no way to tell who that is. I believe this is very useful so you know who flipped a feature (so you can later ask them why they did that, in case it was incorrect to do so). Or just for traceability.

Is there a way to do this? If not, do you think it's worth it? I'm thinking maybe being able to intercept the `payload` and `env` in some way so you can add things to the payload from the `env`.

**Comment by jnunemaker** [comment]
@asterite what is your goal? Are you trying to build an audit log of enable/disable actions?

**Comment by asterite** [comment]
Thank you for replying! <3

We have a notification subscriber that will send a message to Slack telling us "This feature flag was enabled/disabled". We have a staging site where people might be working at the same time so it's nice to know that a flag was changed. However, each of us then has to go to Slack and say "That was me" so that others know they are the ones that changed the flag. It would be really nice if we didn't have to manually go and add our names to the Slack notifications.

If this use case sounds contrived, feel free to close this issue.

**Comment by jnunemaker** [comment]
I'll close the issue, but not contrived, it just isn't something that flipper core is going to support, since auth is very per app thing.  

We did what you are referring to at github. We had middleware that per request kept track of the current user (think middleware that sets `User.current` or something). Then, we'd use that in the active support notifications subscription. From there, we'd store in audit log and post to campfire and then slack. 

Does that help? I will say flippercloud.io has an audit log and track this, but it doesn't post to slack yet. I could add that if it would be valuable to enough people or you were interested in a paid version. I've been thinking about just adding notifications to flippercloud as then people could just get emails or see it in the app. 

For example, this is the speakerdeck.com project in flippercloud:

![Screen Shot 2020-11-18 at 2 19 35 PM](https://user-images.githubusercontent.com/235/99577263-172d7900-29a9-11eb-8076-56286ffd042c.png)

**Comment by asterite** [comment]
> We had middleware that per request kept track of the current user (think middleware that sets User.current or something)

I guess that's a Rack middleware? And it sets a thread-local variable with the current user, and then you access that thread-local variable from the notification subscriber? I might be able to do that.

> since auth is very per app thing

It's true. But this request isn't about auth in particular. It's about providing access to the Rack `env` inside a notification. That way you could include anything from the request or session. That said, looking at the code, it seems a bit hard to do because `Feature` doesn't know about requests and there doesn't seem to be an easy way to change it.

Thank you again, I'll close this and try to implement your suggestion.

**Comment by jnunemaker** [comment]
Yes thread local.

I could expose env but I'm not sure I want to expose env in that area. It would only work if I created a middle ware and people used it but that would work for background jobs. It all comes back to more of a per app thing I think.
