### ISSUE TITLE
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead)

### ISSUE THREAD

**Issue by Hareramrai** [jnunemaker/flipper#493]
I'm using flipper & related gems that are locked in the below version.

```
    flipper (0.20.3)
    flipper-active_record (0.20.3)
      activerecord (>= 5.0, < 7)
      flipper (~> 0.20.3)
    flipper-ui (0.20.1)
      erubi (>= 1.0.0, < 2.0.0)
      flipper (~> 0.20.1)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, < 2.2.0)
```

We are getting this deprecation from `rails(6.1.1)`.

**Comment by jnunemaker** [comment]
There is nothing in flipper related to `connection_config`. I believe this is something related to active record (see [this](https://github.com/rails/rails/pull/38005)), since you are using the active record adapter. Likely you have memoization on and are preloading, so flipper is the first thing that pops the deprecation warning, but I don't believe this is flipper directly. 

Please let me know if I'm wrong.

**Comment by ClaytonPassmore** [comment]
I had the same issue and @jnunemaker was correct - it isn't flipper's fault, it's just that flipper was the first thing to pop the warning.

For me it was actually the [money-rails](https://github.com/RubyMoney/money-rails) gem causing the problem. Upgrading to `1.13.4` fixed it. That might be totally unrelated to what's causing the problem in your app, but just thought I would mention it in case it helps you out :+1:

**Comment by jnunemaker** [comment]
@ClaytonPassmore thanks for confirming and adding more details for the next person!
