### ISSUE TITLE
enable feature for visitors (non users)

### ISSUE THREAD

**Issue by gingerlime** [jnunemaker/flipper#495]
First off: Flipper is awesome! Thank you thank you 🐬 

I have a use-case that I'm not too sure about, so wanted to check.

We currently have a bunch of groups on flipper, e.g.

```ruby
Flipper.register(:customer) { |user| user.customer? }
```

and we then check it using something like

```ruby
flipper[:feature].enabled?(current_user)
```

This works great for logged-in users.

However, we might also want to enable this feature for visitors (non-users), where `current_user` is `nil`.

In this case, `flipper[:feature].enabled?(nil) == false` unless the feature is globally enabled.

I tried to define a group for visitors like this

```ruby
Flipper.register(:visitors) { |user| user.nil? }
```

However, this doesn't seem to work. Passing `nil` to the `enabled?` method doesn't even pass via the group proc ... I'm guessing because it sees that `nil` doesn't respond to `id` or something similar.

I can of course try to wrap the call, and instead of passing `current_user`, pass some kind of a user-like object... It feels much less elegant though, so I'm wondering if I'm missing something?

**Comment by jnunemaker** [comment]
Hey thanks! Glad you are enjoying it. 

Your options:

1. Fully enable the feature. That enables it for actors that are nil (like not signed in visitors).
2. Use the session as actor instead of the user. That allows it to be on all visitors, not just signed in. I have an [example on this issue](https://github.com/jnunemaker/flipper/issues/128#issuecomment-224706391).

 If you are wanting to enable the feature slowly for visitors, then you’ll want to do 2. If enabling all at once is fine, then 1 will work. 

Any reason either of those won’t work for you? Let m know.

Also, I pass all kinds of different actors to `enabled?`. Nothing less elegant about that. It is actually more elegant and designed that way. That is why I call it actor (generic) instead of user (specific). 

At GitHub, we passed in orgs, repositories, users and more. At my current companies, we often use orgs, users and sessions interchangeably.

**Comment by jnunemaker** [comment]
Oh, and passing the session can work fine with groups. 

```ruby
# you can do this
Flipper.register(:customer) { |session| session.respond_to?(:user) && session.user.respond_to?(:customer?) && session.user.customer? }

# or you can delegate customer? to user on session
Flipper.register(:customer) { |actor| actor.respond_to?(:customer?) && actor.customer? }
```

The respond to calls aren’t required, but are handy if you use different types of actors for a given group.

**Comment by gingerlime** [comment]
Thanks @jnunemaker ! That's great option to know. I didn't think about it. 

In my particular use-case I couldn't fully enable it as in 1. I wanted visitors + some logged-in user groups to have the flag enabled, and other logged-in user groups disabled. So option 2 seems to make sense. 

> Also, I pass all kinds of different actors to enabled?. Nothing less elegant about that. It is actually more elegant and designed that way. That is why I call it actor (generic) instead of user (specific).
> 
> At GitHub, we passed in orgs, repositories, users and more. At my current companies, we often use orgs, users and sessions interchangeably.

Can you help me understand this? I understand the register side of things, assuming you accept a session or a duck-typed actor. I'm not sure I fully get the actual feature flag usage side of things? would your code then pass a "real" user or group in some cases, but session in others? how would this affect the UI assignments? (e.g. for assigning individual actor ids, when the `enabled?` check passes a session or a group). Hope I can explain my confusion clearly here... something doesn't quite "click" yet for me, but I'm not sure what it is :)

**Comment by jnunemaker** [comment]
Gotcha. So another way to do it would be to have different checks if signed in or not. 

```ruby
Flipper.register(:visitors) do |actor|
  # returns true for FlipperSession instance and false for User instance (or anything else)
  actor.is_a?(FlipperSession)
end

# turn on feature for visitors
Flipper.enable_group :feature, :visitors

# turn on % of actors, this will only apply to actors that respond to flipper_id
Flipper.enable_percentage_of_actors :feature, 25

if signed_in?
  if Flipper.enabled?(:feature, current_user)
    # do thing
  else
    # dont do thing
  end
else 
  if Flipper.enabled?(:feature, flipper_session)
    # do thing
  else
    # dont do thing
  end
end
```

Checking user if signed in means that 25% of signed in users will have the feature enabled. Checking session if not signed in means I can enable them by % of actor as well or by groups. In the case above, visitors would 100% see the new feature because I enabled the group for the feature. 

I still have to think about it sometimes and I wrote it. :) If that doesn't clear things up let me know. I'd be happy to come up with more examples or do a quick zoom.

**Comment by gingerlime** [comment]
Thanks a bunch @jnunemaker ! I really appreciate it.

The example you gave is very clear, thank you. However it is the kind of thing I was considering as not-so-elegant though, from a caller standpoint though... As the user of flipper, I need to create this wrapper and also do these types of `if/else` to check what to pass over. This is the kind of situation I was trying to avoid...

I'm unfamiliar with the internals, apart from the fact that I saw that there are some checks that an actor is not `nil`. But from a caller perspective, I would love to be able to do something like this:

```ruby
# registration
Flipper.register(:visitors) { |actor| actor.nil? }
Flipper.register(:customers) { |actor| actor.respond_to?(:customer?) }
...

# calling
do_something if Flipper.enabled?(:feature, current_user)
```

I guess the problem is that if you pass `nil`, then you cannot apply a feature only to 25% of `nil`s... right? So then `nil` is only reserved for the case when a feature is fully-enabled if I understand things correctly?

**Comment by jnunemaker** [comment]
You can pass nil. The actor gates will not be used -- individual actor, % of actors and groups (which require actor). 

% of time works with nil. You can set that to 25% but it wouldn't be consistent for an individual visitor as it is completely random. 

In order to have consistency you need to pass something with an id. Session id of some sort is the best way if you want it for signed in and signed out.

**Comment by gingerlime** [comment]
Yup, gotcha. I got a better grasp of things now. Thank you!

> individual actor, % of actors and groups (which require actor).

Theoretically though, `only % of actors` will not work with `nil`, right? individual actors won't match `nil`, groups as well (`nil` does not respond to `customer?` for example)... It's only the percentage that cannot be assigned consistently on `nil` as far as I can tell.

**Comment by jnunemaker** [comment]
Actor gate returns false.

**Comment by jnunemaker** [comment]
actor gate returns false for nil.

https://github.com/jnunemaker/flipper/blob/f398a745b320ef081d9618b58006d6dfb4b7dde6/lib/flipper/gates/actor.rb#L27-L28

% of actors returns false for nil.

https://github.com/jnunemaker/flipper/blob/f398a745b320ef081d9618b58006d6dfb4b7dde6/lib/flipper/gates/percentage_of_actors.rb#L30-L38

group returns false for nil.

https://github.com/jnunemaker/flipper/blob/f398a745b320ef081d9618b58006d6dfb4b7dde6/lib/flipper/gates/group.rb#L27-L34

They check if the thing (aka actor) is wrappable and that returns false for nil.

https://github.com/jnunemaker/flipper/blob/f398a745b320ef081d9618b58006d6dfb4b7dde6/lib/flipper/types/actor.rb#L3-L7

Only boolean and % of time gates will affect enabled? result for nil. I think that makes the most sense because if nil is considered an actor then everyone will have to update their groups and mental model. 

So theoretically, there could be tweaks to those gates to support nil in some way, but I'm not sure it makes sense. 

I think your best bet is to just check the feature for current_user and session.

```ruby
if Flipper.enabled?(:feature, current_user) || (!current_user && Flipper.enabled?(:feature, flipper_session))
  # yep
end
```

We did this all over at GitHub (for User and Repository and Organization). I don't believe it caused any trouble or that it was inelegant. The only thing to keep in mind is that enabling % of actors will do so for all actors. So if you enable 25% of actors and check both current_user and flipper_session, then your feature will be enabled for 25% of users and 25% of sessions.

This allows you to release slowly to everyone and keeps it consistent. If someone is signed in, they'll see the same thing everywhere. If someone is signed out, they'll see the same thing everywhere. 

You can then do groups based on location or permissions or subscriptions or whatever for signed in or signed out.

**Comment by jnunemaker** [comment]
> Is this something that's ok to continue to use, especially in future releases (and current 0.28.0) ?

Yep! I don't see any issues with passing an actor like that.
