### ISSUE TITLE
NameError: uninitialized constant Flipper::Identifier

### ISSUE THREAD

**Issue by davidwessman** [jnunemaker/flipper#518]
## Versions

- rails 5.2.5
- flipper 0.20.4
- flipper-active_record 0.20.4
- flipper-ui 0.20.4

## Initializer

```ruby
# config/initializers/flipper.rb
require "flipper/adapters/active_record"
Flipper.configure do |config|
  config.default do
    Flipper.new(Flipper::Adapters::ActiveRecord.new)
  end
end
```

## Problem

Tried to implement a gate based on [documentation](https://github.com/jnunemaker/flipper/blob/master/docs/Gates.md#2-individual-actor)

```ruby
Flipper::Identifier => NameError: uninitialized constant Flipper::Identifier
```

**Comment by jnunemaker** [comment]
That is in master but not released yet. Should be out soon. 

On April 28, 2021, David Grevink ***@***.***> wrote:
> Versions
>  *  rails 5.2.5
>  *  flipper 0.20.4
>  *  flipper-active_record 0.20.4
>  *  flipper-ui 0.20.4
>
> Initializer
> # config/initializers/flipper.rb require
> "flipper/adapters/active_record" Flipper.configure do |config|
> config.default do Flipper.new(Flipper::Adapters::ActiveRecord.new) end
> end
> ProblemTried to implement a gate based on documentation
> <https://github.com/jnunemaker/flipper/blob/master/docs/Gates.md#2-
> individual-actor>
>
> Flipper::Identifier => NameError: uninitialized constant
> Flipper::Identifier

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/518>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB24EDZLACEOGXO5LJILTK7P7LANCNFSM43WZP67A>.

**Comment by davidwessman** [comment]
Aha! I got an error for missing method on `flipper_id` and did not find it in the documentation.
When I googled for `rails flipper_id` that is the page I got to.

**Comment by jnunemaker** [comment]
Sorry about that. Prior to the unreleased code it was always roll your
own. So until I get this release ready you’ll have to do that. If you
look at the repo you can see the implementation and steal it. I’d link
but I’m on my phone. 

On April 28, 2021, David Grevink ***@***.***> wrote:
> Aha! I got an error for missing method on flipper_id and did not find
> it in the documentation.
>  When I googled for rails flipper_id that is the page I got to.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/518#issuecomment-
828476028>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB24MNWF5WMCXWQOB72LTLAHWNANCNFSM43WZP67A>.

**Comment by davidwessman** [comment]
Yes, I implemented it just like the unreleased code:

```ruby
module Flippable
   extend ActiveSupport::Concern

   def flipper_id
     "#{self.class.name};#{id}"
   end
 end
 ```
 
 Thank you 🙂
