### ISSUE TITLE
Default configuration with memory adapter does not work on rails (puma, webrick)

### ISSUE THREAD

**Issue by kbackowski** [jnunemaker/flipper#529]
Hi.

We've recently upgraded to version 0.21.0 which as i understand introduces default in-memory adapter. This however does not work with puma and webrick. I found that it only works in thin. Rails console and test works fine.

We've added

`gem 'flipper'`

into Gemfile without any additional configuration. Then we're enabling features in `config/environments/development.rb` i.e. :

```
Rails.application.configure do
  Flipper.enable(:foo)
end
```

We try doing this in initializer but no luck as well. 

The app when run rails server using puma or webrick returns that `Flipper.enabled?(:foo)` is false. If we use better_errors to attach to the application process and enable the feature it then works.

We would like to use in memory adapter without simplest configuration in our rails app just to toggle features based on environment. Previously when been initializing flipper using following in config/application.rb:

```
module Foo
  class Application < Rails::Application
    config.flipper = Flipper.new(Flipper::Adapters::Memory.new)
  end
end
```

Then using it everywhere through `Rails.configuration.flipper_instance.enabled?(:foo)`. This worked good and in new version i see that it can still work.

Tested on newest Rails 6.1.3.2

I can provide example repo with this problem for further debug if needed ?

**Comment by jnunemaker** [comment]
I'd love an example repo if that wouldn't take too much time to setup. Thanks!

**Comment by kbackowski** [comment]
@jnunemaker https://github.com/kbackowski/flipper_memory_adapter_issue. Just clone, setup & run rails s, which in this case will run rails using puma for developemnt. On root path you will get `raise 'No'` from following code:

```
if Flipper.enabled?(:foo)
  raise 'YES'
else
  raise 'NO'
end
```

**Comment by jnunemaker** [comment]
The default flipper setup is per thread to avoid thinking about threads for every single bit of state. My gut says that this would work fine with 1 thread and that's what I'll test first. I'll let you know how it goes.

Since that example app has 5 threads, I could see needing to enable in a place where it would happen for each thread. Not sure the best place, but likely in the puma config or you could add some Flipper config to ensure that enable is called for the default adapter.

```ruby
Flipper.configure do |config|
  config.default do
    flipper = Flipper.new(Flipper::Adapters::Memory.new)
    flipper.enable(:foo)
    flipper
  end
end
```

I'll check out these hunches at get back with you.

**Comment by jnunemaker** [comment]
Yep, that is what is happening. I changed this to get some debugging:

```diff 
diff --git a/app/controllers/restaurants_controller.rb b/app/controllers/restaurants_controller.rb
index 0e181ec..b582503 100644
--- a/app/controllers/restaurants_controller.rb
+++ b/app/controllers/restaurants_controller.rb
@@ -3,6 +3,7 @@ class RestaurantsController < ApplicationController
 
   # GET /restaurants or /restaurants.json
   def index
+    p controller: Flipper.adapter.adapter
     if Flipper.enabled?(:foo)
       raise 'YES'
     else
diff --git a/config/database.yml b/config/database.yml
index bb18b5c..6a48ccc 100644
--- a/config/database.yml
+++ b/config/database.yml
@@ -20,8 +20,6 @@ default: &default
   # For details on connection pooling, see Rails configuration guide
   # https://guides.rubyonrails.org/configuring.html#database-pooling
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
-  username: kamil
-  password: kamil
 
 development:
   <<: *default
diff --git a/config/environments/development.rb b/config/environments/development.rb
index 749e61e..8d51f6e 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -14,7 +14,10 @@ Rails.application.configure do
   # Show full error reports.
   config.consider_all_requests_local = true
 
+
+  p before: Flipper.adapter.adapter
   Flipper.enable(:foo)
+  p after: Flipper.adapter.adapter
 
   # Enable/disable caching. By default caching is disabled.
   # Run rails dev:cache to toggle caching.
```

Then started the server with: 

```
env RAILS_MAX_THREADS=1 rails s
```

Then viewed the page. Below is the log output following those changes to print the adapter memory id's. 

Note that the adapter is `Flipper::Adapters::Memory:3960` during boot. But is `Flipper::Adapters::Memory:14760` in the controller. Looks like boot is in different thread than request (controller). 

```
=> Booting Puma
=> Rails 6.1.3.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
{:before=>#<Flipper::Adapters::Memory:3960 name=:memory, source={}>}
{:after=>#<Flipper::Adapters::Memory:3960 name=:memory, source={"foo"=>{:boolean=>"true", :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}}>}
Puma starting in single mode...
* Puma version: 5.3.0 (ruby 3.0.0-p0) ("Sweetnighter")
*  Min threads: 1
*  Max threads: 1
*  Environment: development
*          PID: 4135
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2021-05-19 21:31:27 -0400
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by RestaurantsController#index as HTML
{:controller=>#<Flipper::Adapters::Memory:14760 name=:memory, source={}>}
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 1743)
```

You'll need whatever enable calls you are going to do in the same thread. Or you'll need an adapter that would store across threads -- such as your own thread safe memory adapter or pstore or any other networked adapter. 

If you don't mind a wee bit of config, the example I dropped in my previous comment works. I added this to config/initializers/flipper.rb, restarted the server and on refresh it raised YES even with 5 threads as this makes the enable happen in the same thread. 

```ruby
Flipper.configure do |config|
  config.default do
    flipper = Flipper.new(Flipper::Adapters::Memory.new)
    flipper.enable(:foo)
    flipper
  end
end
```

You could also put the Flipper.enable in a before_action or middleware or anything else that would be run in the same request thread, but that wouldn't cover background jobs. They would also need it, which is why doing it in the `config.default` block works.

Any questions/reactions?

**Comment by jnunemaker** [comment]
For example, if you change your require to:

```
gem 'flipper', require: "flipper/adapters/pstore"
```

Then your sample app will work as is. This just forces the require of pstore adapter which auto-configures it. Then any Flipper calls anywhere will work fine, like in your development.rb file. I tested to be sure.

**Comment by kbackowski** [comment]
Great ! Thank you for this clarification and debug. Will adjust the code an go with configuration block as i would like to keep it simple and use memory adapter in my case.
