### ISSUE TITLE
undefined method `memoize' for #<Flipper::DSL...>

### ISSUE THREAD

**Issue by TerloevIslam** [jnunemaker/flipper#530]
Rails version 6.0.3.7

Can't start the server since update on 0.21.0:

`undefined method memoize' for #<Flipper::DSL:0x00007fcfc8b66a80> (NoMethodError)`

**Comment by jnunemaker** [comment]
What does your configuration look like?

**Comment by TerloevIslam** [comment]
Thanks for the quick reply. Just figured out where the Issue is triggered:
```
Rails.application.configure do
  adapter = Flipper::Adapters::ActiveRecord.new
  config.flipper = Flipper.new(adapter)
end
```

**Comment by TerloevIslam** [comment]
any ideas how to solve it a simple way?

**Comment by jnunemaker** [comment]
You can remove that. Flipper will now configure that for you. 

Just use Flipper.enabled? instead of
Rails.configuration.Flipper.enabled? and it’ll just work. 

On May 18, 2021, David Grevink ***@***.***> wrote:
> any ideas how to solve it a simple way?
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/530#issuecomment-
843145916>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB2Z2SEHARODQMC5HEHLTOJPSTANCNFSM45CGYKIA>.

**Comment by TerloevIslam** [comment]
Looks good, thanks man.

**Comment by jnunemaker** [comment]
Sweet! Let me know if you have any other problems.
