### ISSUE TITLE
Display "feature last accessed at" in flipper-ui

### ISSUE THREAD

**Issue by maxjacobson** [jnunemaker/flipper#543]
Hi there,

We're happy users of the open source version of Flipper and Flipper UI here at Vimeo.

We've made a bunch of features (~100ish) and it's sometimes challenging to manage all of them.

The problem: we suspect that there are several features in our features list which are not actually referenced anywhere in our code anymore. We have around 100 features. It would be nice if the UI could help us identify these so we can delete them and pare down our list.

The solution we're imagining: the table in flipper-ui could have a new "last accessed at" column displaying when was the last time `Flipper[:foo].enabled?` was last called. That would help us identify which features are not being checked anymore.

When an engineer introduces a new feature flag in the code, it would be neat if it automatically showed up in flipper-ui the first time it's checked. That would save us the step of manually adding it. That feels kind of related to this "last accessed at" idea, but perhaps that's a stretch 🙂 .

We'd be happy to try putting together a PR if this sounds like something you'd be interested in. WDYT?

Note: we're currently using 0.17.2, so I apologize if you've made changes in newer versions and we should just upgrade 😅 .

**Comment by jnunemaker** [comment]
Hey! Really glad you dropped an issue here. First, its awesome that Vimeo uses flipper. I didn't know that and that pumps me up. 

> We've made a bunch of features (~100ish) and it's sometimes challenging to manage all of them.

Wow! I love it. I'd also love to chat. It's rare that I get to hear from power users like yourself. If you would be willing to chat, you can snag a time [here](https://calendly.com/nunemaker/chat). I'm out for a couple weeks with a weird schedule but you should be able to get a time after that.

> The problem: we suspect that there are several features in our features list which are not actually referenced anywhere in our code anymore. We have around 100 features. It would be nice if the UI could help us identify these so we can delete them and pare down our list.

Legit problem. At GitHub we used instrumentation to solve this. We instrumented every time enabled? was called to statsd (and later datadog). This gave us a general idea of true/false results and total number of invocations (which we could use to find dead features). 

You can do the same using the automatic instrumentation flipper comes with ([statsd](https://github.com/jnunemaker/flipper/blob/4722a8c78f52a0030abe46be3af9a3a7736edecc/lib/flipper/instrumentation/statsd_subscriber.rb) example).

If you don't want all that and just want the `last_accessed_at`, you could do this:

1. Add a `last_accessed_at` column to flipper features table (assuming you are using flipper active record adapter).
2. Add instrumentation [like this](https://github.com/jnunemaker/flipper/blob/4722a8c78f52a0030abe46be3af9a3a7736edecc/examples/instrumentation_last_accessed_at.rb) to your app (I just added this file as example).
3. Change the instrumentation above to update `last_accessed_at` instead of an in-memory hash. I'd also recommend not updating that more than once a day or something. If you have memcached you could do an `add` for `features/#{feature_name}/last_accessed_at` with a 24 hour expiration around the SQL update. Or however you ensure things only happen on some interval at Vimeo. 

If you have any questions or any of that wasn't helpful, let me know. Closing to keep things tidy here but I'm up for more discussion.

**Comment by maxjacobson** [comment]
@jnunemaker thanks for the thorough reply. Looking forward to chatting in a few weeks.

I see now that we can define our own instrumenter and do whatever we want there, which is cool. It would be fun and useful to surface whatever metadata we record in flipper-ui, because that's where we're looking all the time. But if we need to surface it somewhere else, no worries, we can make do.

I'm curious if you had any additional thoughts on the bonus idea I mentioned. This one: _When an engineer introduces a new feature flag in the code, it would be neat if it automatically showed up in flipper-ui the first time it's checked. That would save us the step of manually adding it._

**Comment by jnunemaker** [comment]
## UI last accessed 

> It would be fun and useful to surface whatever metadata we record in flipper-ui, because that's where we're looking all the time.

Ah yes. Forgot about that. One quick hack would be to set the description_source for the UI to include the last accessed at. 

```ruby
Flipper::UI.configure do |config|
  config.descriptions_source = ->(keys) {
    # select features from database for keys
    # create hash of { String key => "#{description}. Last accessed: #{last_accessed_at}" }
  }
end
```

Because the description source is loaded before each request ([source](https://github.com/jnunemaker/flipper/blob/4722a8c78f52a0030abe46be3af9a3a7736edecc/lib/flipper/ui/actions/feature.rb#L15-L15)), this should work.

If that isn't good enough, we could also do one of these options:

* go more specific and add last_accessed_at similar to description.
* go more generic and make description easier to use for extra bits of info.

## automatically add new features

> When an engineer introduces a new feature flag in the code, it would be neat if it automatically showed up in flipper-ui the first time it's checked. That would save us the step of manually adding it.

`enabled?` is the hot path. So I've intentionally avoided loading any extra data from this method or doing any extra work. 

Thinking on it, this could be done with instrumentation. I'd even be happy to create/merge a PR that accomplished this for people to use (let me know if you want me to put an example together). 

I'm pretty sure I don't want to do this by default though. 

Each enabled call would need to:

* read the set of known features
* check if the feature being checked is a member of that set
* then do a write if not in set. 

Even if this was all cached in memory that would be a lot of extra work for every check. 

I've seen pages on GitHub.com that did thousands of feature checks. Adding this extra work would have been prohibitive. 

All that said, I think we could make an instrumentation thing that would maintain the set in memory though and do this check for those that want it. Wouldn't be an issue for most. I just don't think it should be the default. We might even be able to just make it a config option. `config.auto_add = true` or something. 

Let me know if you have any thoughts either way on any of the above. I'm enjoying the questions! Fun to think through what's possible currently and what should be.
