### ISSUE TITLE
Add shared spec for use in minitest

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#55]
Same as rspec one but works for minitest.

**Comment by AlexWheeler** [comment]
@jnunemaker I'll get started on this

**Comment by jnunemaker** [comment]
Nice. I was thinking the other day that I should just change to minitest. When I started flipper, rspec was way ahead, but I really like minitest these days. That is such an undertaking though I'm never sure it is worth it.

**Comment by AlexWheeler** [comment]
yes minitest is great and one less dependency is always nice since its included in Ruby now. I love this quote on their repo "rspec is a testing DSL. minitest is ruby"

Could be something to add iteratively, especially for new contributors that want to familiarize themselves with the flipper codebase?  But yes would be a big undertaking

**Comment by jnunemaker** [comment]
I suppose we could move a few at a time and just make sure guard, rake and script/test run both minitest and rspec.
