### ISSUE TITLE
flipper-active_record compatibility with Rails 7

### ISSUE THREAD

**Issue by joaotorres** [jnunemaker/flipper#595]
Hey peeps, hope the end of the year is looking good to you all!

The Flipper ActiveRecord adapter docs (https://www.flippercloud.io/docs/adapters/active-record) mention it's only compatible with Rails versions 5 and 6, is support for version 7 coming soon or are there any guidelines on how to use it with Rails 7?

Thanks!

**Comment by jnunemaker** [comment]
Rails 7 support is merged just not released yet. I have to test it in an
app and haven’t had time with the holidays. Maybe tonight!

On December 23, 2021, David Grevink ***@***.***> wrote:
> Hey peeps, hope the end of the year is looking good to you all!
>
> The Flipper ActiveRecord adapter docs
> (<https://www.flippercloud.io/docs/adapters/active-record>) mention
> it's only compatible with Rails versions 5 and 6, is support for
> version 7 coming soon or are there any guidelines on how to use it
> with Rails 7?
>
> Thanks!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/595>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB27C2EITUWNKUIFOTCTUSOI3DANCNFSM5KVRD6YA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by jnunemaker** [comment]
0.23.0 is on its way out. Happy Holidays!
