### ISSUE TITLE
Memoize disabled when set to a proc in application config

### ISSUE THREAD

**Issue by mscoutermarsh** [jnunemaker/flipper#598]
Sharing this incase it's helpful/related to https://github.com/jnunemaker/flipper/pull/586. cc @bkeepers 😄 . Didn't want to leave a huge comment on that PR.

I noticed that memoization had stopped working in our app (related we did recently upgrade to Rails `7.0.1`, not sure if that was the cause).

Our config was in `application.rb` and was set to:

```ruby
config.flipper.memoize = ->(request) { !request.path == "/" }
```

I noticed with that config set, memoization was disabled for all requests and not just ones matching the proc. I tried moving the config to our `initializer` and noticed it seems to be ignored there completely.

Flipper versions:
```
    flipper (0.23.0)
    flipper-active_record (0.23.0)
```

For now I removed the config entirely and have memoize running for all requests. Hopefully this extra info is helpful.

**Comment by bkeepers** [comment]
Hey @mscoutermarsh, I hope you're doing well!

> ```ruby
> config.flipper.memoize = ->(request) { !request.path == "/" }
> ```

I think the proc should be `request.path != "/"`. Right now it's `(!request.path) == "/"` (parenthesis added to highlight Ruby precedence), which will always evaluate to `false == "/"`.

> I tried moving the config to our `initializer` and noticed it seems to be ignored there completely.

#586 is merged, so this should be fixed in master now and will be in the next release.

I've tested this in a new Rails 7 app and it works for me. Let me know if you are still seeing issues.
