### ISSUE TITLE
Allow customizing UI text

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#63]
Each gates text/help/instructions should be customizable so companies/developers can make it feel more like there own. I can also see providing an actor to instance conversion block for changing things like `User:6` to `@jnunemaker` or whatever makes sense.

**Comment by ptrippett** [comment]
We use [rails global ids](https://github.com/rails/globalid) as the flipper_id value which could make this pretty trivial to implement

**Comment by AlexWheeler** [comment]
@jnunemaker what are your thoughts on doing this via the configure block?  similar to how the adapter can be set via [Flipper.configure](https://github.com/jnunemaker/flipper/commit/95bba012463c2a781d10d7a5641b7d6fde2bc7f8#diff-b5a75b6f83af650cc606d47af1581d85R16).

We could have a Flipper::UI.configure.  The downside is *anyone* couldn't customize since it would need to be set in the initializer, but it could work well.

**Comment by jnunemaker** [comment]
@AlexWheeler I like that for anything that needs to be customized. 👍

**Comment by jnunemaker** [comment]
This is done. UI text can now be configured.

**Comment by jnunemaker** [comment]
For more on configuring: https://github.com/jnunemaker/flipper/tree/master/docs/ui#configuration
