### ISSUE TITLE
Accessing flipper results in /flipper%2Ffeatures URL being generated

### ISSUE THREAD

**Issue by patsch** [jnunemaker/flipper#643]
I added flipper to my Rails app

```
gem 'flipper' 
gem 'flipper-active_record' 
gem 'flipper-ui'
```

and mounted it in my `routes.rb` file with a constraint to allow only logged in Admins to access it

```
constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end
```

the contraint works fine (it returns true), however when I access

https://myhost/flipper

the site is immediately redirected to

https://myhost/flipper%2Ffeatures

instead of the correct

https://myhost/flipper/features

(which works and shows up my features as expected)

Any ideas why flipper injects an encoded slash instead of the slash itself ?

I am on Ruby 2.6.5 and Rails 4.2.18 and...
```
  * flipper (0.25.0)
  * flipper-active_record (0.25.0)
  * flipper-ui (0.25.0)
```

Thanks!

**Comment by camallen** [comment]
I came across this issue as well and it's due to the custom Flipper::UI redirect code added in https://github.com/jnunemaker/flipper/commit/530f838818ebb8f7634c19f9f6c7651b544c582e and specifically how it escapes the redirection path via `Rack::Utils.escape_path`.

The problem is only apparent for folks that use rack < v2, folks using rack >=v2 aren't affected.

The issue with the underlying version of `Rack::Utils.escape_path` that's being included via the rails 4 dependency. As at v.1.6.3 https://github.com/rack/rack/blob/47a1fd73fc77f094573f4215b0fc884f4ac1c03c/lib/rack/utils.rb#L43 it relies on the `URI.encode_www_form_component(s)` implementation vs the current functionality landed in rack v2+ via https://github.com/rack/rack/commit/978eb9b9935d388ca8cc45fe31c870b9bc0aaab2 

Upgrading your rack version to v2+ will fix this issue. If that's not possible then you could monkey patch the `redirect_to` method in Flipper::UI to use `::URI::DEFAULT_PARSER.escape s` vs the rack utils version, perhaps via
```
def redirect_to(location)
  status 302
  header 'Location', "#{script_name}#{::URI::DEFAULT_PARSER.escape(location)}"
  halt [@code, @headers, ['']]
end
```

While it's possible to rethink the current `redirect_to` implementation in flipper UI so it safely handles the spaces in feature names (as outlined above). I think it's probably best to close this issue without fixing the underlying rack implementation so we automatically fold in any future improvements to Rack::Utils.

**Comment by bkeepers** [comment]
@camallen thanks for the thorough response.

@patsch are you able to upgrade to Rack >= 2?

**Comment by patsch** [comment]
Thank you very much for the detailed explanation @camallen - the Rails app I am using flipper in is currently locked at Rails 4.2.11 and the ActionPack gem of that Rails version seems to require rack to be of Version 1.6.x

However by adding your suggested monkeypatch in an initializer in config/initializers

```ruby
# see https://github.com/jnunemaker/flipper/issues/643
module Flipper
  module UI
    class Action
      def redirect_to(location)
        status 302
        header 'Location', "#{script_name}#{::URI::DEFAULT_PARSER.escape(location)}"
        halt [@code, @headers, ['']]
      end
    end
  end
end
```

the redirects are now working perfectly :-)
