### ISSUE TITLE
How do I disable logging output

### ISSUE THREAD

**Issue by jnarowski** [jnunemaker/flipper#667]
We have a huge object as an actor and it makes our logs very noise. How do I disable this logging output entirely?

https://jmp.sh/7Wp13yz

**Comment by jnunemaker** [comment]
Hi @jnarowski, that comes from the instrumentation ([source](https://github.com/jnunemaker/flipper/blob/2dc8f6da8d75bc889cf262e7197b2d26a07a4f6d/lib/flipper/railtie.rb#L27-L33)). I think you need to change the default to not be instrumented instead of the [default](https://github.com/jnunemaker/flipper/blob/2dc8f6da8d75bc889cf262e7197b2d26a07a4f6d/lib/flipper/railtie.rb#L19-L25). 

Try a config/initializers/flipper.rb that looks like this and let me know if that helps:

```ruby
Flipper.configure do |config|
  config.default do
    Flipper.new(config.adapter)
  end
end
```

**Comment by jnarowski** [comment]
Nice. Yeah I think that worked. Thanks. I don't quite understand it but glad it cleared the logs.

This is the whole code. Does that still seem correct to you?

```
Flipper.configure do |config|
  config.default do
    Flipper.new(config.adapter)
  end
  if Rails.env.test?
    config.adapter { Flipper::Adapters::Memory.new }
  else
    config.adapter { Flipper::Adapters::ActiveRecord.new }
  end
end
```

**Comment by jnunemaker** [comment]
Yeah. It's because the logging is generated from the instrumentation. 

Another option would have been to change the logger for the flipper log subscriber to a different log file or /dev/null. 

But turning instrumentation off seems best if you aren't using it.

**Comment by bkeepers** [comment]
This should also disable loading the log subscriber:

```ruby
Rails.application.configure do
  config.flipper.log = false
end
```
