### ISSUE TITLE
Referential integrity in autogenerated tables

### ISSUE THREAD

**Issue by llk23r** [jnunemaker/flipper#697]
```
class CreateFlipperTables < ActiveRecord::Migration[6.0]
  def self.up
    create_table :flipper_features do |t|
      t.string :key, null: false
      t.timestamps null: false
    end
    add_index :flipper_features, :key, unique: true

    create_table :flipper_gates do |t|
      t.string :feature_key, null: false
      t.string :key, null: false
      t.string :value
      t.timestamps null: false
    end
    add_index :flipper_gates, [:feature_key, :key, :value], unique: true
  end

  def self.down
    drop_table :flipper_gates
    drop_table :flipper_features
  end
end
```

How does Flipper manage the association between the two tables internally? 

Curious to know if adding something like `t.references :feature, foreign_key: { to_table: :flipper_features }` in `create_table :flipper_gates do |t|...end` would be helpful or if it'll have no impact on ActiveRecord queries with associations. 

If this has already been discussed before, any pointers would be helpful. Thank you!

**Comment by jnunemaker** [comment]
Flipper handles the integrity. It's pretty common in Rails-land to do this. I remember in the past I've hit a lot of sneaky perf (massive cascading deletes, etc.) and issues with foreign keys. I don't really have any interest in using them unless people have good reasons (which I'm always open to hearing). 

I don't think it would make any performance difference for reads since the relevant indexes are already present.
