### ISSUE TITLE
Create group through UI

### ISSUE THREAD

**Issue by alabeduarte** [jnunemaker/flipper#78]
Hi,

I've been trying to create a group from the UI but it seems that's not possible yet. 
Can you confirm that? 

I'm thinking about add a feature on the UI but I'm not sure if it's the best approach according to your original idea of the project. 

What do you think of add a separate button aside "Add Feature", redirecting to a new group creation page? Then I'll be able to see it on the group session. Now the API seems to be the only way. Image below:

![Option 1](http://s2.postimg.org/n39lhteop/Screen_Shot_2015_08_12_at_5_19_50_PM.png)

Another option is add a similar to the actors form but, since a group doesn't belong to a specific feature, I don't know if it is a good idea.

![Option 2](http://s27.postimg.org/jgxxa0k2r/Screen_Shot_2015_08_12_at_5_21_55_PM.png)

What are your thoughts?

Thanks!!

**Comment by jnunemaker** [comment]
Its not possible because groups require a block of ruby code in your code base. Creating a group would have to modify your code or store dynamic stuff in the data store that is eval'd. Both those options seemed like security issues so I don't really think it is possible. Does that make sense? Re-open if not.

**Comment by alabeduarte** [comment]
Ohh, thanks @jnunemaker 

As I saw the created groups on the UI on your examples, I thought that it was a pending stuff to be added in the future.

Thank you!
